// <auto-generated />
using BlazorAppCar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppCar.Migrations
{
    [DbContext(typeof(BlazorAppCarContext))]
    [Migration("20240906172119_AddEngines")]
    partial class AddEngines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RpmMax")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Engine");
                });
#pragma warning restore 612, 618
        }
    }
}
